In [25]:
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

## Obtención y Preparación de Datos

In [26]:
# Descargar los datos
sp500 = yf.download("^GSPC", start="2018-01-01")
sp500.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2018-01-02  2695.810059  2695.889893  2682.360107  2683.729980  3397430000
2018-01-03  2713.060059  2714.370117  2697.770020  2697.850098  3544030000
2018-01-04  2723.989990  2729.290039  2719.070068  2719.310059  3697340000
2018-01-05  2743.149902  2743.449951  2727.919922  2731.330078  3239280000
2018-01-08  2747.709961  2748.510010  2737.600098  2742.669922  3246160000

In [27]:
# Convertir la serie a DataFrame
df_close=sp500[("Close","^GSPC")].to_frame()
df_close.head()

                  Close
                  ^GSPC
Date
2018-01-02  2695.810059
2018-01-03  2713.060059
2018-01-04  2723.989990
2018-01-05  2743.149902
2018-01-08  2747.709961

In [28]:
print(type(df_close))
print(df_close.columns)

<class 'pandas.DataFrame'>
MultiIndex([('Close', '^GSPC')],
           )

In [29]:
# Quitar el MultiIndex
df_close.columns = ['Close']
df_close.head()

                  Close
Date
2018-01-02  2695.810059
2018-01-03  2713.060059
2018-01-04  2723.989990
2018-01-05  2743.149902
2018-01-08  2747.709961

In [30]:
# Verificar valores faltantes
df_close.isna().sum()

Close    0
dtype: int64

## Rendimientos

In [31]:
# Rendimientos
df_close['Simple_Return'] = (df_close['Close'] - df_close['Close'].shift())/df_close['Close'].shift()
df_close.head(5)

                  Close  Simple_Return
Date
2018-01-02  2695.810059            NaN
2018-01-03  2713.060059       0.006399
2018-01-04  2723.989990       0.004029
2018-01-05  2743.149902       0.007034
2018-01-08  2747.709961       0.001662

In [36]:
# Log-rendimientos
df_close['Log_Return'] = np.log(df_close['Close']/df_close['Close'].shift())
df_close.head(5)

                  Close  Simple_Return  Log-Return  Log_Return
Date
2018-01-02  2695.810059            NaN         NaN         NaN
2018-01-03  2713.060059       0.006399    0.006378    0.006378
2018-01-04  2723.989990       0.004029    0.004021    0.004021
2018-01-05  2743.149902       0.007034    0.007009    0.007009
2018-01-08  2747.709961       0.001662    0.001661    0.001661

## Exploración Visual

In [37]:
# Gráfica del precio de cierre
close_graph = px.line(x = df_close.index, y = df_close['Close'])
close_graph.update_layout(title={'text': 'S&P 500 Closing Price', 'x':0.5})
close_graph.update_xaxes(title_text='Date')
close_graph.update_yaxes(title_text='Price')

In [38]:
# Gráfica el Rendimiento Simple
return_graph = px.line(x = df_close.index, y = df_close['Simple_Return'])
return_graph.update_layout(title={'text': 'S&P 500 Simple Return', 'x':0.5})
return_graph.update_xaxes(title_text='Date')
return_graph.update_yaxes(title_text='Return')

In [39]:
# Gráfica el Log-Rendimiento
logreturn_graph = px.line(x = df_close.index, y = df_close['Log_Return'])
logreturn_graph.update_layout(title={'text': 'S&P 500 Log-Return', 'x':0.5})
logreturn_graph.update_xaxes(title_text='Date')
logreturn_graph.update_yaxes(title_text='Return')

### Observaciones

A simple vista es fácil notar que las gráficas de rendimientos tienen una media más estable a través del tiempo, lo cuál hace más útiles estos datos para trabajar con modelos estadísticos.