In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
# Descargar los datos
sp500 = yf.download("^GSPC", start="2018-01-01")
sp500.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2018-01-02  2695.810059  2695.889893  2682.360107  2683.729980  3397430000
2018-01-03  2713.060059  2714.370117  2697.770020  2697.850098  3544030000
2018-01-04  2723.989990  2729.290039  2719.070068  2719.310059  3697340000
2018-01-05  2743.149902  2743.449951  2727.919922  2731.330078  3239280000
2018-01-08  2747.709961  2748.510010  2737.600098  2742.669922  3246160000

In [3]:
# Convertir la serie a DataFrame
df_close=sp500[("Close","^GSPC")].to_frame()
df_close.head()

                  Close
                  ^GSPC
Date
2018-01-02  2695.810059
2018-01-03  2713.060059
2018-01-04  2723.989990
2018-01-05  2743.149902
2018-01-08  2747.709961

In [4]:
print(type(df_close))
print(df_close.columns)

<class 'pandas.DataFrame'>
MultiIndex([('Close', '^GSPC')],
           )

In [5]:
# Quitar el MultiIndex
df_close.columns = ['Close']
df_close.head()

                  Close
Date
2018-01-02  2695.810059
2018-01-03  2713.060059
2018-01-04  2723.989990
2018-01-05  2743.149902
2018-01-08  2747.709961

In [6]:
# Verificar valores faltantes
df_close.isna().sum()

Close    0
dtype: int64

In [7]:
# Rendimientos
df_close['Return'] = (df_close['Close'] - df_close['Close'].shift())/df_close['Close'].shift()
df_close.head(5)

                  Close    Return
Date
2018-01-02  2695.810059       NaN
2018-01-03  2713.060059  0.006399
2018-01-04  2723.989990  0.004029
2018-01-05  2743.149902  0.007034
2018-01-08  2747.709961  0.001662

In [8]:
# Log-rendimientos
df_close['Log-Return'] = np.log(df_close['Close']/df_close['Close'].shift())
df_close.head(5)

                  Close    Return  Log-Return
Date
2018-01-02  2695.810059       NaN         NaN
2018-01-03  2713.060059  0.006399    0.006378
2018-01-04  2723.989990  0.004029    0.004021
2018-01-05  2743.149902  0.007034    0.007009
2018-01-08  2747.709961  0.001662    0.001661